#!/bin/bash

#DIRECTIVES:
#PBS -N SpMV_MPI_Benchmark
#PBS -o ../results/log.out
#PBS -e ../results/log.err

#PBS -q short_cpuQ
#PBS -l walltime=06:00:00
#PBS -l select=4:ncpus=32:mpiprocs=32:mem=32gb

#PBS -M giovanni.todesco@studenti.unitn.it
#PBS -m a
#PBS -m b
#PBS -m e

module load gcc91
module load numactl
module load mpich-3.2.1--gcc-9.1.0

cd "$PBS_O_WORKDIR"

chmod +x benchmark.sh

./benchmark.sh
